### PR TITLE
feat: report telemetry when sandbox login button pressed

### PR DESCRIPTION
**Pull request by dgolovin**
Fix replaces url for a button + command to add telemetry tracking when button pressed

Signed-off-by: Denis Golovin <dgolovin@redhat.com>

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
one problem that I see is that this new way of launching of command is only available in v1.4.0+ so it'll break on all the other versions of Podman Desktop

**Comment by dgolovin** [comment]
@benoitf Shouldn't we have engine compatibility check somewhere [here](https://github.com/containers/podman-desktop/blob/398a19c083a5153ad0982cd37c5ceacac65a6375/packages/main/src/plugin/extensions-updater/extensions-updater.ts#L152) probably? Then if extension requires newer engine version it should not be offered for update or it should indicate update is available, but not compatible with current podman desktop.

**Comment by benoitf** [comment]
@dgolovin until now it was not a priority until now but yes if we want to have newer versions not rolling out to old versions of Podman Desktop it would be a new enhancement.

but engine requirement should require probably to be first exposed at https://registry.podman-desktop.io/api/extensions.json

and I suppose in several other places when we grab "first version" from the list of versions.


coming back to the root problem of this PR

maybe we could check that if we have both href and command, command is used in the markdown implementation

so if we keep both href and command, old versions of Podman Desktop will call the href, and newer versions will call the command (and then telemetry will be reported)

**Comment by dgolovin** [comment]
@benoitf brilliant! it works, but I had to put href in double quotes to avoid parsing issued. Tested on v1.3.1 branch and main.

**Review by benoitf — APPROVED** [review]

**Pull request merged**
