### PR TITLE
Updating sandbox connection status

### PR DESCRIPTION
**Pull request by dgolovin**
Update connection status every 2 seconds.

### CODE REVIEW

**Comment by dgolovin** [comment]
@benoitf How do we usually deal with dependency cycles? The only way I found is intercept warnings and cancel it.

**Comment by benoitf** [comment]
@dgolovin usually we avoid these situations by refactoring the code

**Comment by dgolovin** [comment]
This seems to happen only to external dependencies, because in case of extensions in podman-desktop repository it is not present in extension's node_modules folder.

**Comment by benoitf** [comment]
you could use vite instead of roll-up as in the compose extension

**Pull request merged**
