### PR TITLE
fix: set current context to new sandbox-context

### LINKED ISSUE #102: Set as current context does not set as current context
I tried to login to the dev sandbox and also noticed that by default, checkbox for settings this cluster as current context is enabled. Though, once I was logged in, kubecontext was not changed.

### PR DESCRIPTION
**Pull request by dgolovin**
Fix #102.

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
LGTM. Can't we add a unit test ?

**Review by odockal — CHANGES_REQUESTED** [review]
I agree with @jeffmaury to add unit tests.

**Comment by dgolovin** [comment]
I have to fix https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/25 first then.

**Comment by dgolovin** [comment]
The tests are added to cover connection factory `create` method and `Set as default context` check specifically.

image

Merging.

**Pull request merged**
