### PR TITLE
Added e2e tests prcheck workflow

### PR DESCRIPTION
**Pull request by xbabalov**
Issue: https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/200

### CODE REVIEW

**Review by odockal — CHANGES_REQUESTED** [review]

**Comment by xbabalov** [comment]
This issue prevents the tests from passing https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/245. Tests pass if we delete the resources folder beforehand.

**Review by odockal — APPROVED** [review]
LGTM. Code is working fine, tested locally. although we have a issue on the PR check itself when building extension locally.

**Comment by xbabalov** [comment]
@dgolovin Do you suggest we merge the tests failing on this issue https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/245 or do I delete the needed folder in the PR, we merge them passing and when the issue is fixed they fail and I fix them additionally after that? The passing tests would help when trying to test other PRs later but if the blocker is planned to get fixed soon we can just merge them?

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
